# Generated by Django 5.1.1 on 2024-10-08 08:23

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last name"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of birth"
                    ),
                ),
                (
                    "admission_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Admission date"
                    ),
                ),
                (
                    "leave_date",
                    models.DateField(blank=True, null=True, verbose_name="Leave date"),
                ),
                (
                    "local_subsidy",
                    models.BooleanField(default=True, verbose_name="Local subsidy"),
                ),
                (
                    "food_price",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.foodprice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Child",
                "verbose_name_plural": "Children",
                "ordering": ("last_name", "first_name", "id"),
            },
        ),
    ]
