# Generated by Django 5.1.1 on 2024-10-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_monthlypayment_price"),
        ("kids", "0003_alter_child_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="gov_subsidy",
            field=models.ManyToManyField(to="core.governmentsubsidy"),
        ),
        migrations.AddField(
            model_name="child",
            name="other_subsidy",
            field=models.ManyToManyField(to="core.othersubsidy"),
        ),
    ]
