# Generated by Django 5.1.1 on 2024-10-31 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kids", "0005_remove_child_gov_subsidy_alter_child_local_subsidy_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="child",
            old_name="other_subsidy",
            new_name="other_subsidies",
        ),
    ]
