# Generated by Django 5.1.1 on 2024-10-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("a_date", models.DateField(verbose_name="Date")),
                (
                    "absence_type",
                    models.CharField(
                        choices=[
                            ("R", "reported"),
                            ("NR", "not reported"),
                            ("FR", "first day"),
                            ("O", "other"),
                        ],
                        default="NR",
                        max_length=20,
                        verbose_name="Type of absence",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="Reason"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
