# Generated by Django 5.1.1 on 2024-10-12 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0002_initial"),
        ("kids", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="absence",
            options={"verbose_name": "Absence", "verbose_name_plural": "Absences"},
        ),
        migrations.AlterField(
            model_name="absence",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="changed by",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="absence",
            unique_together={("child", "a_date")},
        ),
    ]
