# Generated by Django 5.1.1 on 2024-10-12 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0003_alter_absence_options_alter_absence_changed_by_and_more"),
        ("kids", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="absence",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="absence",
            constraint=models.UniqueConstraint(
                fields=("child", "a_date"),
                name="child_date_unique",
                violation_error_message="This child's absence for the chosen date is already reported.",
            ),
        ),
    ]
