# Generated by Django 5.1.1 on 2024-10-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0004_alter_absence_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="absence",
            name="child_date_unique",
        ),
    ]
