# Generated by Django 5.1.1 on 2024-10-24 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0005_remove_absence_child_date_unique"),
        ("kids", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absence",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kids.child",
                verbose_name="Child",
            ),
        ),
    ]
