# Generated by Django 5.1.1 on 2024-11-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0002_contribution_amount_alter_contribution_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="name_full",
            field=models.CharField(
                default="", max_length=255, verbose_name="Name for parents"
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="published",
            field=models.BooleanField(default=False, verbose_name="Published"),
        ),
    ]
