# Generated by Django 5.1.1 on 2024-10-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_foodprice_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodprice",
            name="amount",
        ),
    ]
