# Generated by Django 5.1.1 on 2024-10-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_foodprice_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalDayOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
            ],
            options={
                "verbose_name": "Additional day off",
                "verbose_name_plural": "Additional days off",
            },
        ),
    ]
