# Generated by Django 5.1.1 on 2024-10-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_monthlypayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernmentSubsidy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=6, verbose_name="Amount"
                    ),
                ),
            ],
            options={
                "verbose_name": "Government subsidy",
                "verbose_name_plural": "Government subsidies",
            },
        ),
        migrations.CreateModel(
            name="LocalSubsidy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=6, verbose_name="Amount"
                    ),
                ),
            ],
            options={
                "verbose_name": "Local subsidy",
                "verbose_name_plural": "Local subsidies",
            },
        ),
        migrations.CreateModel(
            name="OtherSubsidy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=6, verbose_name="Amount"
                    ),
                ),
            ],
            options={
                "verbose_name": "Other subsidy",
                "verbose_name_plural": "Other subsidies",
            },
        ),
    ]
