# Generated by Django 5.1.1 on 2024-10-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_governmentsubsidy_localsubsidy_othersubsidy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlypayment",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="Amount"
            ),
        ),
    ]
