# Generated by Django 5.1.1 on 2024-11-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_monthlypayment_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionaldayoff",
            options={
                "ordering": ("day",),
                "verbose_name": "Additional day off",
                "verbose_name_plural": "Additional days off",
            },
        ),
    ]
