# Generated by Django 5.1.1 on 2024-11-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accountant",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("EMPLOYEE", "Employee"),
                    ("PARENT", "Parent"),
                    ("ACCOUNTANT", "Accountant"),
                ],
                default="PARENT",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
