# Generated by Django 5.1.1 on 2024-10-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_month", models.DateField(verbose_name="Month")),
                (
                    "food_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=4,
                        verbose_name="Food price",
                    ),
                ),
                (
                    "food_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Food total",
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Monthly payment",
                    ),
                ),
                (
                    "days_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Payable days count"
                    ),
                ),
                (
                    "zus_transfer",
                    models.BooleanField(default=False, verbose_name="ZUS"),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="Paid")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
