# Generated by Django 5.1.1 on 2024-11-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billings", "0003_alter_billing_changed_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billing",
            name="zus_transfer",
        ),
        migrations.AddField(
            model_name="billing",
            name="sub_received",
            field=models.BooleanField(default=False, verbose_name="Subsidies received"),
        ),
    ]
