# Generated by Django 5.1.1 on 2024-11-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billings", "0004_remove_billing_zus_transfer_billing_sub_received"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="gov_subsidy",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6,
                verbose_name="Government subsidy",
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="info",
            field=models.TextField(
                blank=True, null=True, verbose_name="Information for parents"
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="local_subsidy",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="Local subsidy"
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Note"),
        ),
        migrations.AddField(
            model_name="billing",
            name="other_subsidies",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6,
                verbose_name="Other subsidies",
            ),
        ),
    ]
