# Generated by Django 5.1.1 on 2024-11-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billings", "0005_billing_gov_subsidy_billing_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="info_subsidies",
            field=models.TextField(
                blank=True, null=True, verbose_name="Information about other subsidies"
            ),
        ),
    ]
