# Generated by Django 5.1.1 on 2024-11-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billings", "0006_billing_info_subsidies"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="tag",
            field=models.CharField(
                blank=True,
                choices=[("yellow", "yellow"), ("green", "green")],
                max_length=255,
                null=True,
                verbose_name="tag",
            ),
        ),
    ]
