# Generated by Django 5.1.1 on 2024-11-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billings", "0007_billing_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="confirmed",
            field=models.BooleanField(default=False, verbose_name="Confirmed"),
        ),
        migrations.AddField(
            model_name="billing",
            name="sent",
            field=models.BooleanField(default=False, verbose_name="Sent"),
        ),
    ]
