# Generated by Django 5.1.1 on 2024-11-11 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billings", "0009_billing_child_name"),
        ("kids", "0007_alter_child_other_subsidies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="child",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="kids.child"
            ),
        ),
    ]
