# Generated by Django 5.1.1 on 2024-10-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(verbose_name="Date")),
                (
                    "topic",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Topic"
                    ),
                ),
                (
                    "activity",
                    models.TextField(
                        blank=True, null=True, verbose_name="Kids activity"
                    ),
                ),
                (
                    "movement",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motor activity"
                    ),
                ),
                (
                    "music",
                    models.TextField(
                        blank=True, null=True, verbose_name="Musical activity"
                    ),
                ),
                (
                    "art",
                    models.TextField(
                        blank=True, null=True, verbose_name="Art activity"
                    ),
                ),
                ("other", models.TextField(blank=True, null=True, verbose_name="Inne")),
            ],
        ),
        migrations.CreateModel(
            name="MainTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Main Topic",
                "verbose_name_plural": "Main Topics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_date", models.DateField(verbose_name="Date")),
                (
                    "breakfast",
                    models.TextField(blank=True, null=True, verbose_name="Breakfast"),
                ),
                ("soup", models.TextField(blank=True, null=True, verbose_name="Soup")),
                (
                    "lunch",
                    models.TextField(blank=True, null=True, verbose_name="Lunch"),
                ),
                (
                    "teatime",
                    models.TextField(blank=True, null=True, verbose_name="Teatime"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note_date", models.DateField(verbose_name="Date")),
                ("content", models.TextField(verbose_name="Content")),
            ],
        ),
    ]
