# Generated by Django 5.1.1 on 2024-11-18 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0003_alter_maintopic_changed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activities",
            name="main_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="info.maintopic",
            ),
        ),
    ]
