# Generated by Django 5.1.1 on 2024-11-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0004_alter_activities_main_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="activities",
            name="special_event",
            field=models.TextField(
                blank=True, null=True, verbose_name="Dodakowe wydarzenia"
            ),
        ),
    ]
